# Configurations
title: Return-Zero;
longtitle: Return-Zero;
author: Jieun
email: kjeun990806@gmail.com
description: >
  des.

version: 1.0
gitbook_version: 3.2.3

url: "https://jeun-990806.github.io"
baseurl: ""
rss: RSS

favicon_path: /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown: kramdown

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

cc:
  - aa
  - bb
